entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificateResolvers:
  myresolver:
    acme:
      email: activator112233@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
