entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    
  rdp:
    address: ":3389"

#certificatesResolvers:
#  myresolver:
#    acme:
#      email: le@rillo5000.com
#      storage: acme.json
#      httpChallenge:
#        # used during the challenge
#        entryPoint: web

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
#  file:
#    filename: /etc/traefik/dynamic.yml
#    watch: true
