entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    
  rdp:
    address: ":3389"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
